ermongroup/cs228-notes

preliminaries/probabilityreview/index.md
Trivial syntax issues
Signed-off-by: Anand Avati <avati@cs.stanford.edu>
=> probability review: syntax fixes

inference/ve/index.md
Computation of marginal probability p(l) in student's example was wrong.
There were mixed notions of p(s|i) and p(s|d) in the example, and hence computation of factors, $\tau_2$ and $\tau_3$, were incorrect.
=> Fix: Example (student’s grade)

representation/undirected/index.md
Replacing the few instances of "Bayes net" with "Bayesian networks" to make the style consistent (the latter term is almost always used).
=> Suggestion to improve style

representation/undirected/index.md
It's possible that $$p$$ should be $$G$$ (please verify this suggestion is correct before accepting it).
=> Fixing possible typo in undirected/index.md

inference/jt/index.md
Signed-off-by: Anand Avati <avati@cs.stanford.edu>
=> fix backslash

inference/sampling/index.md
Signed-off-by: Anand Avati <avati@cs.stanford.edu>
=> fixes in importance sampling example

learning/latent/index.md
sigma Q should be the weighted variance.
=> changed learning latent

learning/structLearn/index.md
a -> an
algorithm -> algorithms
--amr6114
=> Update structure learning - grammar

inference/jt/index.md
listed a lot of typos on piazza, changed the ones that are left
=> listed typos/questions on piazza (https://piazza.com/class/ixgrcpncxmq5c?cid=388), changed the ones that haven't already been changed yet

docs/representation/directed/index.html
Corrected factorization expression.
=> Corrected factorization expression.

preliminaries/introduction/index.md
I think it shoud be
```
... in the form of a probability ...
```
instead of 
```
... in the form probability ...
```
=> Fix minor typo

representation/directed/index.md
According to the Figure, SAT score depends on intelligence, not the test's difficulty.
=> Corrected slight error in equation.

preliminaries/introduction/index.md
=> fix the typo for preliminaries introduction

extras/vae/index.md
=> fix a typo in vae

preliminaries/probabilityreview/index.md
add missing bracket in Var definition for: preliminaries_probabilityreview_index.md section 2.5
=> add missing bracket in var definition for probability review section 2.5

representation/directed/index.md
In 'Probabilistic modeling with Bayesian networks' section
=> Replace index variable i with appropriate value

inference/ve/index.md, preliminaries/applications/index.md, preliminaries/introduction/index.md
Fix some typos in the introduction.
=> Fix minor typos.

inference/jt/index.md
=> Pluralize 'message'

css/tufte.scss, docs/css/tufte.css, docs/inference/jt/index.html, docs/inference/ve/index.html, docs/preliminaries/applications/index.html, preliminaries/applications/index.md
Formatting improvements in Applications page for now.  I will be updating content over the next few days.
=> Improved Applications Page, Rebuilt site

inference/sampling/index.md
Clarified explanation of the Gibbs sampling procedure. In particular, I added the point that at each time step, when we update a variable x_i, we immediately use its new value for sampling other variables x_j, which is not mentioned in the current version of the notes. 
PS: to see the main differences between the current writeup of gibbs sampling algorithm with my explanation, see the commit with hash starting with ce1423f ; subsequent commits were done to improve the formatting of my initial commit.
=> Clarified Gibbs sampling section

preliminaries/probabilityreview/index.md
Seems like the dy and dx here aren't needed, since it's not an integral and the expression would appear to be correct without them.
=> Probability Review typos?

learning/directed/index.md
Added missing log symbol to section on MLE in Bayesian Networks
=> Added missing log symbol

learning/bayesianlearning/index.md
Math-mode is now correctly applied to the figure, and the figure is correctly formatted in the sidebar.
=> Fixed Beta distribution figure in Bayesian Learning

preliminaries/probabilityreview/index.md
The "it" was potentially ambiguous here; just tidied up some of the language.
=> Clarifying wording in the chain rule explanation

preliminaries/probabilityreview/index.md
Added the frequently used phrase, "Assigning value x to random variable X" to clarify for other students whose probability may be a little rusty.
=> Clarifying sentence on random variable assignment.

learning/structLearn/index.md
Mostly some grammar/style changes to clarify the points in the Recent Advances section.
=> Fixed some typos

README.md, index.md
1. Updated CS228 course page link in README.md
2. Updated CS228 course page link in index.md
=> CS 228 Course Link Update

inference/ve/index.md
I want to make explicit why this example is O(d^4) running time.
=> Update Running Time of VE

preliminaries/applications/index.md
Found an incorrect link to Radford's paper in Real-world applications chapter.
=> Fix reference link in Applications

preliminaries/applications/index.md, representation/directed/index.md, representation/undirected/index.md
I fixed the inconsistent indices of factors in representation/undirected and changed the order of x_i and y_i in one equation.
=> Fix factor indices

extras/vae/index.md
First of all thank you so much for sharing these lecture notes. These have been extremely helpful for me!
Please take a look at my changes, which I believe make sense given the context.
Best Regards,
Ted
=> Replaced p(x) with p(x|z) for VAE decoder

representation/directed/index.md
I thought that this proof was helpful for understanding the intuition behind the provided fact. It might be nice to give students a precise reference to easily find this proof (or I can add it into these notes directly)
=> Add textbook reference for proof

preliminaries/probabilityreview/index.md
Here's a first draft of changes to the probability theory preliminaries section, with Kuno as reviewer and Mayee as editor.
=> Probability theory section edits
