ermongroup/cs228-notes

- representation/undirected/index.md
Should be ϕ(X,Y) instead of ϕ(A,B).
> fix notation inconsistency

- inference/sampling/index.md
Detailed balance is sufficient and not necessary (instead of the other way around). Notes now link to a paper which does [MCMC without satisfying detailed balance](https://arxiv.org/pdf/1007.2262.pdf) to show that this is possible and sometimes desirable.
> fixed typo in detailed balance

- preliminaries/probabilityreview/index.md
Move $$'s so that the word "where" is not inside equation
> Fix formatting of 2.6

- preliminaries/probabilityreview/index.md
Missing $ and subscripts added.
> fixed some typos

- learning/structLearn/index.md
- Duplicate characters for \mid 
- Joint distribution of graph and params incorrectly defined due to typo
> Fix math typo in definitions

- extras/vae/index.md
I believe this is a typo.
From my understanding, we approximate sampling z from a distribution x through an intermediate transformation that takes an epsilon + distribution and outputs a z.
Thus, it should be g(\epsilon, x) not g(z, \epsilon)(also swapped order of parameters around to preserve notation of previous definition).
Credit to @isaykatsman for originally bringing up the typo.
> Fixed typo in section on reparametrization trick

- preliminaries/probabilityreview/index.md
I have gone through the probability review notes "preliminaries/probabilityreview/index.md", and fixed the format (especially math symbols) and typos I could find. 
I don't know how to convert markdown to html, so the corresponding html is not updated.
> Fix the format and typos of probability review notes

- preliminaries/probabilityreview/index.md
Split the long equations and fix equations that were not displayed.
> Fix the math equation format for probability review

- representation/undirected/index.md
Minor thing: I've mostly seen this spelled as [cut-set](https://en.wikipedia.org/wiki/Cut_(graph_theory)) or [cut set](http://mathworld.wolfram.com/CutSet.html). Although [cutset](https://en.wiktionary.org/wiki/cutset) also seems to valid be less frequently used.
> cutset vs cut-set or cut set

- inference/jt/index.md
Corrects a simple typo at the end of the junction tree chapter.
> JT : 'may not converges' -> 'converge'

- inference/sampling/index.md
Changing "g" -> "f" in a place where there was no g to refer to, moving the part about what T^t means to when it's being used, "is" -> "into" typo fix
> Typo fixes

- inference/jt/index.md
Putting (RIP) after "running intersection property" instead of just after "running intersection", saying what the name sepset comes from (so the term hopefully sticks better/is less mysterious), and adding some missing subscripts.
> Three small polishes

- inference/map/index.md
Updating max expressions to be more rigorous/correct (since the log of phi(c) isn't phi(c)). Used theta_c to match the lecture slides and the thetas used later in this lecture notes entry (which were originally used without introduction).
Alternatively, we could define phi(c) to be a log-likelihood, but we should make that more clear if we do (eg when talking about the Potts model, say "log likelihood of..." rather than "likelihood" of).
> Fixing log of phi issue

- learning/bayesianlearning/index.md
This fixes the misalignment between the equations and the text on the Bayesian Learning page.
> Corrected misalignment

- representation/directed/index.md
Used to say, "Let I(p) denote the set of all CONDITIONAL independencies that hold for a distribution p" but the example given is just a regular ol' independence rather than an explicit conditional independence. So I changed it to say "the set of all independencies" which aligns with the example and with the PGM textbook.
> Clarify I-Maps

- preliminaries/probabilityreview/index.md
Corrected Erratum in 2.5 Variance example, in the E[X] formula where fx should be fX
> Fix 2.5 variance example typo fx to fX

- inference/map/index.md
- judging from the example figure, in the display formula in the
Graphcuts section, $\lambda_{st}$ should be $\lambda_{uv}$, because the
costs seem to depend on the edge.
> fixed a typo?

- inference/jt/index.md
I think that the equation on line 50 in the BP and JT notes is missing a factor of $$\phi(x_i)$$. Since local single node potentials are included in the messages sent from $$x_k$$ to $$x_j$$ in the preceding equation, shouldn't we consider the local single node potential at node $$x_i$$ when computing its marginal?
> Corrected equation for sum-product message passing

- inference/jt/index.md
- inference/ve/index.md
- learning/undirected/index.md
- representation/undirected/index.md
1) Single-variable marginals are proportional to (not equal to) product of messages. This is because the product of unnormalized factors is still unnormalized.
2) Fix other typos in JT and VE inference.
Also fixed some typos (replacing `..` and `...` with `\dotsc`)
> Fix typos in JT and VE inference

- representation/undirected/index.md
Minor fix so that it doesn't sound like it's staying that Bayesian networks cannot perfectly represent certain distributions---but rather that Bayesian networks cannot encode certain independence assumptions in its structure.
> fix statements about directed networks

- inference/jt/index.md
- inference/sampling/index.md
- learning/directed/index.md
\propto is unnecessary, since p already has a tilde over it, indicating that it is unnormalized. Can be replaced with an equal sign.
> Typo correction -- propto to equal, Asymptotically unbiased definition corrected in Sampling, MCMC alg fixed in Sampling

- preliminaries/applications/index.md
- representation/directed/index.md
I found an unnecessary word 'to' in the sentence that specifies the construction of DAG in representation/directed.
> Fix unnecessary to

- preliminaries/probabilityreview/index.md
There are some events (sets of outcomes in Omega) that can't be distinguished just by using the CDF on the random variable X. For example, if your X(omega) is "sum of number of heads over 2 (non-independent) coin flips", then you can't use the CDF of X to compute the probability of the event containing the single outcome "first get a head, then get a tails". In this example, you the closest you can get by using the CDF is you can compute the probability of the event containing the two outcomes "first head then tails" and "first tails then heads".
> Weaken claim about CDF of X

- representation/directed/index.md
This typo could be found in the third bullet point on this page.
> Add missing "the"

- inference/variational/index.md
I think it should be "support of p" because we estimate p by q.
> p instead of q

- learning/latent/index.md
Shouldn't the thetas be called parameters for the general EM algorithm? They are weights when we specifically discuss a mixture model, but not in general. I find parameters to be more suitable.
> weights or parameters?

- representation/directed/index.md
Fix the invalid link to the interactive web simulation tool for showcasing d-separation
> Update the index.md of Bayesian Network

- representation/directed/index.md
In the section _Probabilistic modeling with Bayesian networks_, I believe the intended formulation might be "which will often be the case in the problem**s** we will consider" 🙂
> Pluralise "problem"

- inference/ve/index.md
The link in the notes was broken for me but the archive.org version seems to still be running
> Update variable elimination web app link with archived version
